### ISSUE TITLE
Transparent Window

### ISSUE THREAD

**Issue by teroni** [DonZooles/project-omega#6]
Is there an option to adjust the transparency that is applied when I apply the skin? I love the layout/skin, but I don't need to see behind the window.

**Comment by teroni** [comment]
Pull request #8 will make this change easier for people to adjust themselves. Possibly add to the documentation how to adjust it?

**Comment by DonZooles** [comment]
What kind of documentation do you mean? I think I could open a new page for modifications on the wiki

**Comment by teroni** [comment]
Already added! Redid my commit to add it to the install instructions. I only did english version, as I can't speak german.

**Comment by DonZooles** [comment]
Ok, all manuals updated, thanks for your participation. :)
